version: "3.8"

services:
  web:
    build:
      context: ./llm-eval-frontend
      dockerfile: Dockerfile
    container_name: llm-eval-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production